version: "3.8"
services:
  backend:
    build: ./apps/portal-python
    env_file:
      - ./apps/portal-python/.env
    ports:
      - "8000:8000"

  ui:
    build: ./apps/portal-ui
    ports:
      - "5173:5173"
    # For prod you probably want to serve via nginx inside the image (Dockerfile set up)
